### ISSUE TITLE
Create a script that automatically performs tests 

### ISSUE THREAD

**Issue by manugh1** [dan-koller/Spring-Anti-Fraud-System#20]
https://github.com/dan-koller/Spring-Anti-Fraud-System/blob/d58572bbcb70a049812eef30922d44bfcf637185/README.md?plain=1#L452

# Add scripts for Windows and Mac/Linux

- [X] Add a bash script for automating tests
- [x] Add a powershell script
- ~~Add logic to those scripts so they can detect the current machine and perform the tests for different databases (mysql, postgres) and systems (homebrew, arm, etc.)~~

**Comment by dan-koller** [comment]
Creating a bash and powershell (or batch) script sounds like a good idea! Feel free to implement this feature and open a pr.
